### ISSUE TITLE
Add token logoURIs (potentially just placeholders)

### ISSUE THREAD

**Issue by TomAFrench** [element-fi/elf-tokenlist#8]
Currently all tokens here don't have any icons which means that we get rather ugly placeholder icons appear in their place.

It doesn't look like you have a set design what the icons for a pToken or yToken should look like but for any Element-specific assets I think just adding the Element logo would be sufficient for an MVP? This would at least show at a glance in external UIs that the asset belongs to the Element ecosystem.

This could be done in conjunction with #7 to give icons just to the pTokens or yTokens if desired as logos for the underlying assets would exist in other tokenlists.

**Comment by DannyDelott** [comment]
This is a valid point 👍 I'll add this.
